services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=zxcghouls
      - POSTGRES_USER=user
      - POSTGRES_DB=ckmz_database
    volumes:
      - ./data/db:/var/lib/postgresql/data/
  web:
    build: ./client-app
    ports:
      - "3000:3000"
    volumes:
      - ./client-app:/client-app
  api:
    build: ./api        
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
