services:
  # db:
  #   container_name: db
  #   image: postgres:14-alpine
  #   ports:
  #     - '5432:5432'
  #   healthcheck: 
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data/
  web:
    build: ./client-app
    ports:
      - "3000:3000"
    volumes:
      - ./client-app:/client-app
  api:
    build: ./api        
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    environment:
      - DJANGO_SUPERUSER_PASSWORD=123qweZXC
    command: >
      bash -c "python manage.py collectstatic --noinput &&
                python manage.py makemigrations &&
                python manage.py migrate &&
                
                python manage.py runserver 0.0.0.0:8000"
    #вставить в 36 строку (если не редачился этот файл) для создания сюзера
    # python manage.py createsuperuser --no-input --username superuser --email qwerty@gmail.com &&


    # depends_on:
    #   db:
    #     condition: service_healthy
